### ISSUE TITLE
Using more than three slaves

### ISSUE THREAD

**Issue by cryptomulde** [Zeppelin500/MBusino#15]
Hello,

thank you for the solution. It is exactly what I am looking for and helps me get my planned meters into HA.
 
I want to setup my house using four Engelmann Sensostar U. (Basement --> start, ground floor, first floor, second floor)

In the readme it says we are limited to three devices? What causes these limitations? Could it be avoided or do I just setup a secondary esp to tackle the problem?

**Comment by Zeppelin500** [comment]
The limitation is from the M-Bus Master (and from the Code, but can be changed). The master provides the slaves with power.
A tiny DC/DC converter converts 5V to 36V. The limitation of 3 is only estimated. Nobody has tested yet. You can try it, **but I recommend two M-Businos**.
Another problem ist that the time between the requests (min. ~5sec.)will be added per slave.

You can also try the Zihatec Master. Specification says max. 6 Slaves. But the Zihatec Master need a additional power supply and will not fit mechanically to MBusino. Also you has to use an ESP32 S2 mini, because the serial of ESP 8266 and the Zihatec Master are no friends.

**Comment by cryptomulde** [comment]
Thank you for your detailed explanation. I adapted the setup so I will only use three meters.

I want to setup the following way:

"primary-wire" roof-meter running to first-floor-meter --> first-floor-meter --> basement (wago)

"secondary-wire" ground-floor meter --> basement (wago)

Can I connect primary and secondary wire in a wago and connect the whole bunch to mbusino? 

Would this still be considered a daisy chain or do I have to run in a row --> roof --> first floor --> ground floor --> mbusino?

**Comment by Zeppelin500** [comment]
See chapter 2.5, the wiring doesn't matter.
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.molline.de/fileadmin/content/content/Downloads/Info-Datenbl%25C3%25A4tter/iDB1011_MBus_Installationshinweise.pdf&ved=2ahUKEwjD87CBk5WGAxW5a_EDHQFNAQUQFnoECB4QAQ&usg=AOvVaw1_SBwBU12T78EIN_Jo34_9
